null checks consistency across SexHospitalListeners
Resolves:

ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.campaign.CampaignFleetAPI.getFleetData()" because the return value of "com.fs.starfarer.api.campaign.SectorAPI.getPlayerFleet()" is null
java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.campaign.CampaignFleetAPI.getFleetData()" because the return value of "com.fs.starfarer.api.campaign.SectorAPI.getPlayerFleet()" is null
        at data.scripts.intel.SexHospitalShipListener.reportFleetMemberDeployed(SexHospitalShipListener.java:18)